pull_request_title: 'Update translation from Crowdin'
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    type: android
    dest: /app/strings.xml
  - source: /xposed/src/main/res/values/strings.xml
    translation: /xposed/src/main/res/values-%two_letters_code%/%original_file_name%
    type: android
    dest: /xposed/strings.xml
