name: Sync to Module repo

on:
  push:
    branches: [ "master" ]
  release:
    types: [ "published" ]

jobs:
  sync-readme:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Clone Module repo
        run: |
          git clone https://x-access-token:${{ secrets.MODULE_REPO_TOKEN }}@github.com/${{ vars.MODULE_REPO }}.git ModuleRepo

      - name: Copy & Modify file
        run: |
          README_FILE="README.md"
          cp "$README_FILE" ModuleRepo/$README_FILE
          cd ModuleRepo
          SOURCE_LINK="## [🔗 源码仓库](https://github.com/Meteor2333/YourMIUI)"
          sed -i "s|<!-- Source Link -->|$SOURCE_LINK|" "$README_FILE"

          EXTRACTED=$(mktemp)
          SUMMARY_FILE="SUMMARY"
          awk '/^- \[x\]/ { sub(/^- \[x\] /, ""); print }' "$README_FILE" > "$EXTRACTED"
          EMPTY_LINE=$(grep -n "^$" $SUMMARY_FILE | head -n 1 | cut -d: -f1)
          if [ -z "$EMPTY_LINE" ]; then
            echo "No empty line found, appending at end"
            cat "$EXTRACTED" >> $SUMMARY_FILE
          else
            head -n $EMPTY_LINE $SUMMARY_FILE > temp.md
            echo "" >> temp.md
            cat "$EXTRACTED" >> temp.md
            mv temp.md $SUMMARY_FILE
          fi

      - name: Commit & Push to Module repo
        run: |
          cd ModuleRepo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "sync README.md file" || echo "No changes"
          git push
  sync-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download assets
        run: |
          mkdir assets
          echo '${{ toJson(github.event.release.assets) }}' | jq -c '.[]' | while read asset; do
            url=$(echo $asset | jq -r '.browser_download_url')
            name=$(echo $asset | jq -r '.name')
            curl -L -o "assets/$name" "$url"
          done

      - name: Publish to Module repo
        uses: softprops/action-gh-release@v3
        with:
          repository: ${{ vars.MODULE_REPO }}
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          files: assets/*
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.MODULE_REPO_TOKEN }}
